import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MadaProvider } from "./lib/components/provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Madabel",
  description: "Generated by create next app",
  icons: {
    icon: '/madabel-icon.png',
    shortcut: '/madabel-icon.png',
    apple: '/madabel-icon.png'
  }
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <Toaster position="top-right" />
        <MadaProvider> {children}</MadaProvider>
         
        
      </body>
    </html>
  );
}
